spring.application.name=smart-queue

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_queue
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update